# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 中国R会议
email: contact@cos.name
description: 中国R会议是中国R语言和数据科学的重要会议，由中国最大的统计学门户网站——统计之都（https://cosx.org/）主办。
keywords: R语言, 数据科学, 数据分析, 数据挖掘, 机器学习, 商业智能, 大数据
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://china-r.org" # the base hostname & protocol for your site

qiniubaseurl: "http://chinar.xueqingtv.com"  # qiniu CDN speedup

# Build settings
markdown: kramdown
permalink: /:year/:title
